### ISSUE TITLE
Update Website for Milestone 1

### ISSUE THREAD

**Issue by KaileeHung** [mochi-bytes/mochi-bytes.github.io#2]
- [x] Added videos and synopsis
- [x] Kailee: Wrote description for work, and reformatted the site
- [x] Carol: Wrote description for work done on shop screen.
- [x] Kristyn: Created and added logo
